# Filebeat Configuration for AI Study Circle
# Log shipping and collection configuration

# Filebeat global settings
filebeat.registry.path: /usr/share/filebeat/data/registry

# Input configurations
filebeat.inputs:
  # Backend Winston log files
  - type: log
    enabled: true
    paths:
      - /logs/backend/*.log
    fields:
      service: backend
      environment: ${ENVIRONMENT:development}
      logtype: winston
    fields_under_root: false
    multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
    multiline.negate: true
    multiline.match: after
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: message
    processors:
      - add_host_metadata:
          when.not.contains.tags: forwarded
      - add_docker_metadata: ~
    tags: ["backend", "winston", "ai-study-circle"]
  
  # Frontend log files (JSON format)
  - type: log
    enabled: true
    paths:
      - /logs/frontend/*.json
      - /logs/frontend/*.log
    fields:
      service: frontend
      environment: ${ENVIRONMENT:development}
      logtype: frontend-json
    fields_under_root: false
    json.keys_under_root: true
    json.add_error_key: true
    processors:
      - add_host_metadata:
          when.not.contains.tags: forwarded
    tags: ["frontend", "json", "ai-study-circle"]
  
  # Docker container logs
  - type: container
    enabled: true
    paths:
      - '/var/lib/docker/containers/*/*.log'
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true
    condition:
      contains:
        docker.container.name: "ai-study"

# Module configurations
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
  reload.period: 10s

# Processors
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_docker_metadata: ~
  - timestamp:
      field: timestamp
      layouts:
        - '2006-01-02T15:04:05.000Z'
        - '2006-01-02T15:04:05Z'
      test:
        - '2025-10-25T10:30:45.123Z'
  - drop_fields:
      fields: ["agent", "ecs", "host.mac", "host.architecture"]

# Output configuration
output.logstash:
  hosts: ["logstash:5044"]
  compression_level: 3
  bulk_max_size: 2048
  template.name: "ai-study-logs"
  template.pattern: "ai-study-logs-*"

# Alternative: Direct Elasticsearch output (disable if using Logstash)
# output.elasticsearch:
#   hosts: ["http://elasticsearch:9200"]
#   index: "ai-study-logs-%{+yyyy.MM.dd}"
#   template.name: "ai-study-logs"
#   template.pattern: "ai-study-logs-*"

# Logging configuration
logging.level: info
logging.to_files: true
logging.files:
  path: /usr/share/filebeat/logs
  name: filebeat
  keepfiles: 7
  permissions: 0644

# Monitoring
monitoring.enabled: true
monitoring.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

# HTTP endpoint for health checks
http.enabled: true
http.host: 0.0.0.0
http.port: 5066

# Setup configuration
setup.template.enabled: false
setup.ilm.enabled: false
setup.dashboards.enabled: false

# Performance settings
queue.mem:
  events: 4096
  flush.min_events: 512
  flush.timeout: 5s

# SSL settings (if needed)
# ssl.verification_mode: none