# Kibana Configuration for AI Study Circle
# Dashboard and visualization configuration

# Server settings
server.name: "ai-study-kibana"
server.host: 0.0.0.0
server.port: 5601
server.basePath: ""
server.rewriteBasePath: false
server.maxPayload: 1048576

# Elasticsearch settings
elasticsearch.hosts: ["http://elasticsearch:9200"]
elasticsearch.username: ""
elasticsearch.password: ""
elasticsearch.preserveHost: true
elasticsearch.ssl.verificationMode: none

# Kibana index
kibana.index: ".kibana"
kibana.defaultAppId: "dashboard"

# Security settings (disabled for development)
xpack.security.enabled: false
xpack.encryptedSavedObjects.encryptionKey: "a7a6311933d3503b89bc2dbc36572c33a6c10925682e591bffcab6911c06786d"

# Monitoring settings
monitoring.enabled: true
monitoring.kibana.collection.enabled: false

# UI settings
newsfeed.enabled: false
telemetry.enabled: false
telemetry.optIn: false

# Dashboard settings
dashboard.defaultDarkMode: false

# Logging settings
logging.appenders:
  default:
    type: console
    layout:
      type: json
logging.loggers:
  - name: http.server.response
    level: debug

# Advanced settings
map.includeElasticMapsService: false
data.search.aggs.shardDelay.enabled: true

# CSV export settings
xpack.reporting.csv.maxSizeBytes: 10485760

# Spaces settings
xpack.spaces.enabled: true

# Machine Learning (if needed)
xpack.ml.enabled: false

# Canvas (if needed)
xpack.canvas.enabled: true

# Developer tools
console.enabled: true
dev_tools.enabled: true

# Status page
status.allowAnonymous: true